// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"terminal-blog-api/config"
	"terminal-blog-api/model"
)

// Injectors from wire.go:

func InitBlog() model.Result {
	configConfig := config.InitConfig()
	result := model.InitDatabase(configConfig)
	return result
}
